---
- name: Configure System
  hosts: localhost
  connection: local
  become: true
  roles:
    - role: common
      tags: [common]
    - role: chrome
      tags: [chrome]
    - role: antigravity
      tags: [antigravity]
    - role: gnome
      become: false
      tags: [gnome]
